### ISSUE TITLE
google.protobuf.text_format.ParseError: 8:5 : Message type "second.protos.VoxelNet" has no field named "num_class".

### ISSUE THREAD

**Issue by Joiequ** [RickOnEarth/pointpillars_based_CLOCs#1]
Hello, I have the following error while running the code. How can I solve it?
config_path:  configs/pointpillars/car/xyres_16.proto
Traceback (most recent call last):
  File "pytorch/train.py", line 883, in <module>
    fire.Fire()
  File "/home/cqu123/anaconda3/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/cqu123/anaconda3/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/cqu123/anaconda3/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "pytorch/train.py", line 615, in evaluate
    text_format.Merge(proto_str, config)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/cqu123/anaconda3/envs/pointpillars/lib/python3.6/site-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 8:5 : Message type "second.protos.VoxelNet" has no field named "num_class".

**Comment by gdb123** [comment]
have the same error as u, did u solve it?
